name: demo.push

on:
  workflow_run:
    workflows: [demo.pr]
    types: [completed]
    branches: [test]

jobs:
  depoly_test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
          echo ${{secrets.ENV_NAME}}
          echo ${{secrets.GCLOUD_TEST_CREDENTIALS}}
          echo Depoly start to run
