# This is a basic workflow to help you get started with Actions

name: Ketchup-main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #   push:
  #     branches: [ "main" ]
  #   pull_request:
  #     branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches:
      - test
      - stg
      - main
    inputs:
      functionType:
        description: 'function type'
        required: true
        default: 'trigger'
        type: choice
        options:
          - trigger
          - notifier
          - record
      triggerFunctionName:
        description: 'trigger name'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - abandoned_offer
          - abandonment
          - applepie
          - coffee_upsell
          - coffeecoupon
          - dessert
          - full_onboarding
          - lto_upsell
          - occasion
          - onboarding
          - popular_dessert
      notifierFunctionName:
        description: 'notifier name'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - full_onboarding
      recorderFunctionName:
        description: 'recorder name'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - begin_checkout
          - checkout_go_to_confirm_order
          - choose_store
          - first_open
          - map_select_store
          - purchase
          - search_results_select_store
          - use_counter_coupon
          - use_mop_coupon

#env:
#  FunctionType: ${{ inputs.functionType }}
#  TriggerFunctionName: ${{ inputs.triggerFunctionName }}
#  NotifierFunctionName: ${{ inputs.notifierFunctionName }}
#  RecorderFunctionName: ${{ inputs.recorderFunctionName }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  read-branch:
    runs-on: ubuntu-latest
    if: ${GITHUB_REF##*/}  == 'test' || ${GITHUB_REF##*/}  == 'stg' || ${GITHUB_REF##*/}  == 'main'
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [read-branch]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set output
        id: vars
        run: ｜
          echo ::set-output name=branch::${GITHUB_REF#refs/*/}
          echo ::set-output name=functionType::$FunctionType
          echo ::set-output name=triggerFunctionName::$TriggerFunctionName
          echo ::set-output name=notifierFunctionName::$NotifierFunctionName
          echo ::set-output name=recorderFunctionName::$RecorderFunctionName
        env:
          FunctionType: ${{ inputs.functionType }}
          TriggerFunctionName: ${{ inputs.triggerFunctionName }}
          NotifierFunctionName: ${{ inputs.notifierFunctionName }}
          RecordFunctionName: ${{ inputs.recorderFunctionName }}

      - name: Check output
        run: |
          echo ${{ steps.vars.outputs.branch }}
          echo ${{ steps.vars.outputs.functionType }}
          echo ${{ steps.vars.outputs.triggerFunctionName }}
          echo ${{ steps.vars.outputs.notifierFunctionName }}
          echo ${{ steps.vars.outputs.recorderFunctionName }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_TEST_CREDENTIALS }}
      # Runs customer-defined-script
      - name: Run a CRD script
        run: |
          cd functions; sh hello.sh

      - name: Update dev branch
        run: |
          gcloud functions list
#          cd functions/test_latency
#          make deploy-dev
#          gcloud functions list
