# This is a basic workflow to help you get started with Actions

name: Read

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #   push:
  #     branches: [ "main" ]
  #   pull_request:
  #     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches:
      - test
      - stg
      - main
    inputs:
      functionType:
        description: 'function type'
        required: true
        default: 'trigger'
        type: choice
        options:
          - trigger
          - notifier
          - record
      triggerFunctionName:
        description: 'trigger name'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - abandoned_offer
          - abandonment
          - applepie
          - coffee_upsell
          - coffeecoupon
          - dessert
          - full_onboarding
          - lto_upsell
          - occasion
          - onboarding
          - popular_dessert
      notifierFunctionName:
        description: 'notifier name'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - full_onboarding
      recorderFunctionName:
        description: 'recorder name'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - begin_checkout
          - checkout_go_to_confirm_order
          - choose_store
          - first_open
          - map_select_store
          - purchase
          - search_results_select_store
          - use_counter_coupon
          - use_mop_coupon


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  read:
    runs-on: ubuntu-latest
    if: ${GITHUB_REF##*/}  == 'main'
    steps:
      - name: Read branch name
        run: echo continue build


  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs-on: [read]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs customer-defined-script
      - name: Run a CRD script
        run: |
          cd functions; sh hello.sh

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
